version: '3.1'
services:
  server:
    container_name: server
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATASOURCE_HOST=db
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=account-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root